### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by g0dzcsgo** [3vasion/Encore-Server-Resources#1]
Do you mind sharing the database for the server? the one that was used and called "sesx" can't be bothered re-creating all sql tables, you can clear users n shit just need all the tables & columns etc.

Willing to pay!

Discord: coolcs#4816

**Comment by OkapiSound** [comment]
SQL pls? discord : OkapiSound#1930. tnx ! dm me and will speak about it.

**Comment by g0dzcsgo** [comment]
Changed my discord to cool#1337..

OkapiSound#1930 didnt work

**Comment by 3vasion** [comment]
yeah ive got the sql just shoot me a message on discord

3vasion#3495
